node_js: 6
script:
  - npm install
  - npm run lint
  - npm run test:coverage
after_success:
  - npm run codecov
deploy:
  provider: npm
  email: Frizz925@hotmail.com
  api_key: $NPM_TOKEN 
  on:
    tags: true
